# Generated by Django 3.2.5 on 2022-12-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20221212_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_words_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
