# Generated by Django 3.2.5 on 2022-12-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='Igor Strelnikov', max_length=255),
        ),
    ]
